name: keep workflow alive
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,3,20 * *'

jobs:
  commit-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: empty commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "empty commit"
          git push origin main
